config/routes.rb
PostRails::Application.routes.draw do
  root "pages#home"
    get "about" => "pages#about"

  get "/register", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  resources :users, only: [:show, :create, :edit, :update]

  resources :posts do
    member do
      post "vote" 
    end  
    resources :comments, only: [:create, :destroy] do
      member do
        post "vote"
      end  
    end  
  end  

  resources :categories, only: [:new, :create, :show]  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :body,
    presence: true
end  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user, only: [:new, :create, :destroy]

  def create
    @post = Post.find_by slug: params[:post_id]
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.creator = current_user
    
   # @comment = @post.comments.build(params.require(:comment).permit(:body))

    if @comment.save
      flash[:notice] = "You created a comment!"
      redirect_to post_path(@post)
    else
      render "posts/show"
    end  
  end

  def destroy
    
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted!"
        else
          flash[:error] = "You can only vote on a comment once!"
        end   
        redirect_to :back
      end
      format.js
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end  

app/views/comments/_comment.html.erb
<% show_post ||= false %>
<h5><%= comment.body %></h5>
<% if show_post %>
  <p>commented on <em><%= link_to comment.post.title, post_path(comment.post) %></em></p>
<% end %>

<div class="votes">
  <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: "post", remote: true do %>
    <i class="icon-hand-up" id="upvote"></i> 
  <% end %>
  <span id="comment_<%= comment.id %>_votes"><%= comment.total_votes %> votes</span>
  <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: "post", remote: true do %>
    <i class="icon-hand-down" id="downvote"></i> 
  <% end %>
</div>

<% if logged_in? && comment.creator == current_user %>
  <i class="icon-user" id="user_show_icon"></i>
<% end %>
<%= link_to comment.creator.username, user_path(comment.creator) %> -
<small class="muted">
  commented <%= time_ago_in_words(comment.created_at) + " ago" %>
</small>

app/views/comments/vote.js.erb
<% if @vote.valid? %>  
  $("#comment_<%= @comment.id %>_votes").html("<%= @comment.total_votes %> votes")
<% else %>
  alert("Oops, you can only vote on a comment once");
<% end %>  