config/routes.rb
PostRails::Application.routes.draw do
  root "pages#home"
    get "about" => "pages#about"

  get "/register", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  resources :users, only: [:show, :create, :edit, :update]

  resources :posts do
    member do
      post "vote" 
    end  
    resources :comments, only: [:create, :destroy] do
      member do
        post "vote"
      end  
    end  
  end  

  resources :categories, only: [:new, :create, :show]  
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title,
    presence: true,
    length: {minimum: 5}

  validates :description,
    presence: true

  validates :url,
    presence: true,
    uniqueness: true

  sluggable_column :title   
end  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :vote]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update]

  def index
     @posts = Post.all.page(params[:page]).order("created_at DESC").per_page(14)
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = "Your post was created!"
      redirect_to posts_path
    else
      render :new
    end  
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = "You updated the post!"
      redirect_to post_path(@post)
    else
      render :edit
    end  
  end

  def destroy
    if @post.destroy
      flash[:notice] = "You successfully deleted your post!"
      redirect_to posts_path
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = 'You can only vote on a post once.'
        end
        redirect_to :back
      end
      format.js
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by slug: params[:id]
  end

  def require_creator
    access_denied unless logged_in? and (current_user == @post.creator || current_user.admin?)
  end 
end  

app/views/posts/_form.html.erb
<div class="well">
  <%= form_for @post do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: "span5", placeholder: "Title goes here" %>
  
      <%= f.label :url %>
      <%= f.text_field :url, class: "span5", placeholder: "URL goes here" %>

      <%= f.label :description %>
      <%= f.text_area :description, class: "span5", placeholder: "Description goes here", rows: "6" %>

      <div class="control-group">
        <%= f.label "Categories" %>
        <hr>
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <% cb.label(class: "checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
        <% end %>
      </div>
  
    <div class="button">  
      <%= f.submit @post.new_record? ? "Create Post" : "Update Post", class: "btn btn-primary" %>
    </div>
  <% end %>
</div> 

app/views/posts/_post.html.erb
<%= render post.categories %>
<h3><%= link_to post.title, post_path(post) %></h3>
<h4><%= post.description %></h4>

<div class="votes">
  <%= link_to vote_post_path(post, vote: true), method: "post", remote: true do %>
    <i class="icon-hand-up" id="upvote"></i>
  <% end %>
  <span id="post_<%= post.slug %>_votes"><%= post.total_votes %> votes</span>
  <%= link_to vote_post_path(post, vote: false), method: "post", remote: true do %>
    <i class="icon-hand-down" id="downvote"></i>
  <% end %>
</div>

<small class="muted">
  <%= link_to pluralize(post.comments.count, 'comment'), post_path(post) %>
  | posted by <%= link_to post.creator.username, user_path(post.creator) %> <%= time_ago_in_words(post.created_at) + ' ago' %>
  <% if logged_in? && (current_user == post.creator || current_user.admin?) %>
    | <i class="icon-user"></i>
    <div class="pull-right">
      [ <i class="icon-pencil" id="glyphs"></i> <%= link_to "Edit", edit_post_path(post) %> 
      | <i class="icon-trash" id="glyphs"></i> <%= link_to "Delete", post, method: :delete, data: {confirm: "Are you sure your want to delete this post?"} %> ]
    </div>
  <% end %>
</small>  

app/views/posts/edit.html.erb
<%= render "shared/errors", obj: @post %>

<div class="page-header">
  <h2>Edit Post<small> - go ahead and do some updating</small></h2>
</div> 
<%= render "form" %>

app/views/posts/index.html.erb
<div class="page-header">
  <% if logged_in? %>
    <h2>Welcome <small> - <%= current_user.username %>, start posting!</small></h2>
  <% else %>
    <h2>Welcome <small> - please <%= link_to "register", register_path %> to get started!</small></h2>
  <% end %>
</div>

<% @posts.each do |post| %>
    <div class="row">
      <div class="span1">
        <div class="gravatar_post"><%= link_to image_tag(post.creator.gravatar_url), user_path(post.creator) %></div>
      </div>
      <div class="span11">
        <div id="post_feed">
          <%= render 'post', post: post %>
        </div>
      </div>
    </div>
<% end %>
<%= will_paginate @posts %>

app/views/posts/new.html.erb
<%= render "shared/errors", obj: @post %>
<div class="page-header">
  <h2>New Post<small> - create a new rails post!</small></h2>
</div> 
<%= render "form" %>

app/views/posts/show.html.erb
<%= render "shared/errors", obj: @comment %>
<div class="row">
  <div class="span1">
    <div class="gravatar_post_show"><%= link_to image_tag(@post.creator.gravatar_url), user_path(@post.creator) %></div>
  </div>  
  
  <div class="span11">
    <div class="page-header" id="show_post">
      <%= render @post.categories %>
        <div class="pull-right"><i class="icon-arrow-left" id="glyphs"></i> <%= link_to "Back to Posts", posts_path %></div>
        <h3 class="strong_title"><%= @post.title %></h3>
        <hr>
        <h4><%= @post.description %></h4>

        <div class="votes">
          <%= link_to vote_post_path(@post, vote: true), method: "post", remote: true do %>
            <i class="icon-hand-up" id="upvote"></i>
          <% end %>
          <span id="post_<%= @post.id %>_votes"><%= @post.total_votes %> votes</span>
          <%= link_to vote_post_path(@post, vote: false), method: "post", remote: true do %>
            <i class="icon-hand-down" id="downvote"></i>
          <% end %>
        </div>
        
        <small class="muted">
          posted by <%= link_to @post.creator.username, user_path(@post.creator) %> <%= time_ago_in_words(@post.created_at) + " ago" %> |
          <%= link_to 'go to link', display_url(@post.url) %>
          <% if logged_in? && (current_user == @post.creator || current_user.admin?) %>
            | <i class="icon-user" id="glyphs"></i>        
            <div class="pull-right">
              [ <i class="icon-pencil" id="glyphs"></i> <%= link_to "Edit", edit_post_path(@post) %>
              | <i class="icon-trash" id="glyphs"></i> <%= link_to "Delete", @post, method: :delete, data: {confirm: "Are you sure your want to delete this post?"} %> ]
            </div> 
          <% end %>  
        </small>
    </div>   

    <% if logged_in? %>
        <%= form_for [@post, @comment] do |f| %>
            <%= f.text_area :body, class: "span11", rows: "7", placeholder: "Comment goes here" %>
          <div class="button">  
            <%= f.submit "Create comment", class: "btn btn-primary" %> 
          </div>
        <% end %>
    <% end %>  
      <div id="all_comments">
        <h4 class="strong_title">Comments</h4>
      </div>

    <% @post.comments.each do |comment| %>
      <div id="comment_feed">
        <div class="row">
          <div class="span0">
            <div class="gravatar_comment"><%= link_to image_tag(comment.creator.gravatar_url), user_path(comment.creator) %></div>
          </div>

          <div class="span8">
            <%= render "comments/comment", comment: comment %>
          </div>  
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%= @post.slug %>_votes").html("<%= @post.total_votes %> votes")
<% else %>
  alert("Oops, you can only vote on a post once!")
<% end %>