config/routes.rb
PostRails::Application.routes.draw do
  root "pages#home"
    get "about" => "pages#about"

  get "/register", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  resources :users, only: [:show, :create, :edit, :update]

  resources :posts do
    member do
      post "vote" 
    end  
    resources :comments, only: [:create, :destroy] do
      member do
        post "vote"
      end  
    end  
  end  

  resources :categories, only: [:new, :create, :show]  
end

app/views/layouts/_footer.html.erb
<div class="navbar navbar-fixed-bottom">
  <div class="navbar-inner">
    <div class="container footer text-center">
      <h6>Developed by <%= link_to "Marco Roman", about_path %></h6>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div id="flash_messages">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
</div>  

app/views/layouts/_modal.html.erb
<div class="modal-login">
  <div class="modal hide fade" id="myModal" aria-hidden="true" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-header">
      <h3>Please Login to Continue</h3>
    </div>

    <div class="modal-body">
      <div class="well">
        <%= form_tag '/login' do %>
          <%= label_tag :username %>
          <%= text_field_tag :username, nil, :placeholder=>"Username goes here" %>

          <%= label_tag :password %>
          <%= password_field_tag :password, nil, :placeholder=>"Password goes here" %>

          <div class="button">
          <%= submit_tag "Login", class: 'btn btn-primary' %>
          </div>
        <% end %>
        <hr>
        <small><%= link_to 'Register New Account', register_path %></small>
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Close</button>
     </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <%= link_to "Post Rails", root_path, :class => "brand" %>
 
      <div class="nav-collapse collapse">
        <ul class="nav">
          <% if logged_in? %>
            <li class="divider-vertical"></li>
            <li class="active"><%= link_to "All Posts", posts_path %></li>
            <li class="divider-vertical"></li>
          <li><%= link_to "About", about_path %></li>
          <% else %>
            <li class="active"><%= link_to 'Home',  root_path %></li>
            <li class="divider-vertical"></li>
            <li><%= link_to "All Posts", posts_path %></li>
            <li class="divider-vertical"></li>
            <li><%= link_to 'About',  about_path %></li>
          <% end %>
        </ul>

        <ul class="nav pull-right">
          <% if logged_in? %>
            <li><%= link_to "New Post", new_post_path %></li>
            <li class="divider-vertical"></li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Categories<span class="caret"></span>
              </a>  
              <ul class="dropdown-menu">
                <% Category.all.each do |category| %>
                  <li><%= link_to category.name, category_path(category) %></li>
                <% end %>

                <% if logged_in? and current_user.admin? %>
                  <li class="divider"></li>
                  <li>
                    <%= link_to (new_category_path) do %>
                      <i class="icon-plus"></i>
                      New Category
                    <% end %>  
                  </li>
                <% end %>
              </ul>
            </li>
            
            <li class="divider-vertical"></li>
            <li class="dropdown">
              <%= link_to("#", class: "dropdown-toggle", "data-toggle" => "dropdown") do %>
                <div id="gravatar_nav">
                  <%= image_tag(current_user.gravatar_url) %>
                  <%= current_user.username %><span class='caret'></span>
                </div>
              <% end %>

              <ul class="dropdown-menu">
                <li><%=link_to user_path(current_user) do %><i class="icon-user" id="user_glyphs"></i>User Profile<% end %></li>
                <li><%= link_to edit_user_path(current_user) do %><i class="icon-pencil" id="user_glyphs"></i>Edit Profile<% end %></li>
                <li class="divider"></li>
                <li><%= link_to logout_path do %><i class="icon-circle-arrow-left" id="user_glyphs"></i>Logout<% end %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Register", register_path %></li>
            <li class="divider-vertical"></li>
            
            <!-- Modal Link Trigger Action -->
            <li><%= link_to 'Login', login_path, :remote => true, "data-toggle" => "modal", "data-target" => "#myModal" %></li>
          <% end %>    
        </ul>  
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Rails</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    
    <%= render "layouts/navigation" %>
    <%= render "layouts/modal" %>

    <div class="container">
      <%= render "layouts/messages" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
 
  </body>
</html>